### ISSUE TITLE
增加数据库连接后，生成native文件启动失败

### ISSUE THREAD

**Issue by ljxwjj** [dudiao/solon-native-example#4]
<dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>5.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>wood-solon-plugin</artifactId>
        </dependency>
增加这两个依赖后，生成native文件启动失败

[Solon] App: Start loading
15:22:52.434 [ForkJoinPool.commonPool-worker-1] INFO org.noear.solon.Solon - Logging: console {level=TRACE, enable=true}
15:22:52.436 [main] INFO org.noear.solon.Solon - App: Plugin starting
15:22:52.438 [main] INFO org.noear.solon.Solon - Session: Local session state plugin is loaded
15:22:52.448 [main] INFO org.noear.solon.Solon - View: load: FreemarkerRender
15:22:52.449 [main] INFO org.noear.solon.Solon - View: load: org.noear.solon.view.freemarker.FreemarkerRender
15:22:52.449 [main] INFO org.noear.solon.Solon - View: mapping: .ftl=FreemarkerRender
15:22:52.449 [main] INFO org.noear.solon.Solon - App: Bean scanning
org.noear.solon.core.exception.InjectionException: Injection failed: com.lvlian.websocket.Config::dataSource
        at org.noear.solon.core.BeanContainer.beanInject(BeanContainer.java:580)

        at org.noear.solon.core.AopContext.lambda$initialize$6(AopContext.java:198)
        at org.noear.solon.core.AopContext.tryInject(AopContext.java:463)
        at org.noear.solon.core.AopContext.tryBuildBean(AopContext.java:591)
        at org.noear.solon.core.AopContext.tryCreateBeanOfMethod0(AopContext.java:498)
        at org.noear.solon.core.AopContext.tryCreateBeanOfMethod(AopContext.java:481)
        at org.noear.solon.core.AopContext.lambda$initialize$0(AopContext.java:127)
        at org.noear.solon.core.AopContext.lambda$tryCreateBeanOfClass0$15(AopContext.java:523)
        at org.noear.solon.core.AopContext.tryCreateBean0(AopContext.java:548)
        at org.noear.solon.core.AopContext.tryCreateBeanOfClass0(AopContext.java:519)
        at org.noear.solon.core.AopContext.tryCreateBeanOfClass(AopContext.java:510)
        at org.noear.solon.core.AopContext.lambda$beanScan$11(AopContext.java:423)
        at java.base@17.0.6/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base@17.0.6/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base@17.0.6/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base@17.0.6/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base@17.0.6/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base@17.0.6/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base@17.0.6/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base@17.0.6/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.noear.solon.core.AopContext.beanScan(AopContext.java:417)
        at org.noear.solon.core.AopContext.beanScan(AopContext.java:388)
        at org.noear.solon.SolonApp.run(SolonApp.java:197)
        at org.noear.solon.SolonApp.start(SolonApp.java:96)
        at org.noear.solon.Solon.start(Solon.java:153)
        at org.noear.solon.Solon.start(Solon.java:116)
        at com.lvlian.websocket.App.main(App.java:15)
Caused by: org.noear.snack.exception.SnackException: create instance error, clas
s com.zaxxer.hikari.HikariDataSource
        at org.noear.snack.core.utils.BeanUtil.newInstance(BeanUtil.java:88)
        at org.noear.snack.to.ObjectToer.analyseBean(ObjectToer.java:505)
        at org.noear.snack.to.ObjectToer.analyse(ObjectToer.java:127)
        at org.noear.snack.to.ObjectToer.handle(ObjectToer.java:39)
        at org.noear.snack.core.Context.handle(Context.java:117)
        at org.noear.snack.ONode.to(ONode.java:996)
        at org.noear.snack.ONode.toObject(ONode.java:966)
        at org.noear.solon.extend.impl.PropsConverterExt.convert(PropsConverterExt.java:41)
        at org.noear.solon.core.BeanContainer.beanInjectConfig(BeanContainer.java:750)
        at org.noear.solon.core.BeanContainer.beanInjectDo(BeanContainer.java:645)
        at org.noear.solon.core.BeanContainer.beanInject(BeanContainer.java:576)

        ... 26 more
Caused by: java.lang.NoSuchMethodException: com.zaxxer.hikari.HikariDataSource.<init>()
        at java.base@17.0.6/java.lang.Class.getConstructor0(DynamicHub.java:3585)
        at java.base@17.0.6/java.lang.Class.getDeclaredConstructor(DynamicHub.java:2754)
        at org.noear.snack.core.utils.BeanUtil.newInstance(BeanUtil.java:85)
        ... 36 more
Exception in thread "main" java.lang.IllegalStateException: SolonApp start failed
        at org.noear.solon.Solon.start(Solon.java:163)
        at org.noear.solon.Solon.start(Solon.java:116)
        at com.lvlian.websocket.App.main(App.java:15)
Caused by: org.noear.solon.core.exception.InjectionException: Injection failed:com.lvlian.websocket.Config::dataSource
        at org.noear.solon.core.BeanContainer.beanInject(BeanContainer.java:580)

        at org.noear.solon.core.AopContext.lambda$initialize$6(AopContext.java:198)
        at org.noear.solon.core.AopContext.tryInject(AopContext.java:463)
        at org.noear.solon.core.AopContext.tryBuildBean(AopContext.java:591)
        at org.noear.solon.core.AopContext.tryCreateBeanOfMethod0(AopContext.java:498)
        at org.noear.solon.core.AopContext.tryCreateBeanOfMethod(AopContext.java:481)
        at org.noear.solon.core.AopContext.lambda$initialize$0(AopContext.java:127)
        at org.noear.solon.core.AopContext.lambda$tryCreateBeanOfClass0$15(AopContext.java:523)
        at org.noear.solon.core.AopContext.tryCreateBean0(AopContext.java:548)
        at org.noear.solon.core.AopContext.tryCreateBeanOfClass0(AopContext.java:519)
        at org.noear.solon.core.AopContext.tryCreateBeanOfClass(AopContext.java:510)
        at org.noear.solon.core.AopContext.lambda$beanScan$11(AopContext.java:423)
        at java.base@17.0.6/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base@17.0.6/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base@17.0.6/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base@17.0.6/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base@17.0.6/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base@17.0.6/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base@17.0.6/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base@17.0.6/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.noear.solon.core.AopContext.beanScan(AopContext.java:417)
        at org.noear.solon.core.AopContext.beanScan(AopContext.java:388)
        at org.noear.solon.SolonApp.run(SolonApp.java:197)
        at org.noear.solon.SolonApp.start(SolonApp.java:96)
        at org.noear.solon.Solon.start(Solon.java:153)
        ... 2 more
Caused by: org.noear.snack.exception.SnackException: create instance error, class com.zaxxer.hikari.HikariDataSource
        at org.noear.snack.core.utils.BeanUtil.newInstance(BeanUtil.java:88)
        at org.noear.snack.to.ObjectToer.analyseBean(ObjectToer.java:505)
        at org.noear.snack.to.ObjectToer.analyse(ObjectToer.java:127)
        at org.noear.snack.to.ObjectToer.handle(ObjectToer.java:39)
        at org.noear.snack.core.Context.handle(Context.java:117)
        at org.noear.snack.ONode.to(ONode.java:996)
        at org.noear.snack.ONode.toObject(ONode.java:966)
        at org.noear.solon.extend.impl.PropsConverterExt.convert(PropsConverterExt.java:41)
        at org.noear.solon.core.BeanContainer.beanInjectConfig(BeanContainer.java:750)
        at org.noear.solon.core.BeanContainer.beanInjectDo(BeanContainer.java:645)
        at org.noear.solon.core.BeanContainer.beanInject(BeanContainer.java:576)

        ... 26 more
Caused by: java.lang.NoSuchMethodException: com.zaxxer.hikari.HikariDataSource.<init>()
        at java.base@17.0.6/java.lang.Class.getConstructor0(DynamicHub.java:3585)
        at java.base@17.0.6/java.lang.Class.getDeclaredConstructor(DynamicHub.java:2754)
        at org.noear.snack.core.utils.BeanUtil.newInstance(BeanUtil.java:85)

**Comment by dudiao** [comment]
抱歉，刚看到。看错误是 hikari 没有兼容 graalvm native ，连接数据库这块还没测试，之后会先找 solon 官方的项目做 native 集成

**Comment by dudiao** [comment]
已经支持HikariCP和wood

https://github.com/dudiao/solon-native-example/commit/e1f6924cfe3c4de9e63a1c960a66196f1a1f2678
